### ISSUE TITLE
SHDW/USDC "Links" section still points to the old Serum markets

### ISSUE THREAD

**Issue by perezsan** [aldrin-exchange/aldrin-registry#40]
The new market works (yay!), but when you call down the dropdown menu and look at the Live markets, the SHDW/USDC Market ID is incorrect for everything under 'Links", i.e. the market is incorrect when you click on 'i' for info, and also when you hover over the 'world icon, then click on the solscan.io external link.

Market ID should be 77a32S2KQhJ4rUMKuZmoG4WrKDBiN6VXB6CzhUd7BsnH for the new OpenSerum market.

**Comment by rindeveloper** [comment]
Hey, should be fixed now, thanks for reporting!
